# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site
title: 'DentistSmile | Dental Jekyll Theme'
description:  "A responsive Jekyll theme for dental clinics."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Logo
logo: 'svg/logo.svg'

# Colors

brandColor:             '#3dadb2'
backgroundColor:        '#f7f7f7'
textColor:              '#555'

# Animation
clientAnimation:        'bounceOut'



# server
port:    7777

# transfer
markdown:    kramdown

# Sass
sass: 
    sass_dir: assets/css/
    style: nested
    

# Exclude files
exclude: [
    .gitignore,
    .sass-cache
]


